### ISSUE TITLE
urn:cts:botcar

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite2-sns-registry#1]
Please supply the following information.

Subnamespace abbreviation:  botcar

URI for the subnamespace: http://folio.furman.edu/botcar

Summary description (one line) of the corpus identified by this subnamespace:  Texts published with CTS from the Botanica Caroliniana digital library; travelogues, natural philosophy, and documents from the first two centuries of European exploration of the Carolinas.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: http://folio.furman.edu/projects/botanicacaroliniana/index.html

**Comment by neelsmith** [comment]
This is note a cite2urn.
