### ISSUE TITLE
urn:cts:fufolio

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite2-sns-registry#2]
Please supply the following information.

Subnamespace abbreviation:  fufolio

URI for the subnamespace: http://folio.furman.edu/folio

Summary description (one line) of the corpus identified by this subnamespace:  Research and teaching texts from the Department of Classics at Furman University.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: http://folio.furman.edu

**Comment by neelsmith** [comment]
This is not a cite2 URN.
