### ISSUE TITLE
urn:cite2:fufolio

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite2-sns-registry#3]
Please supply the following information.

Subnamespace abbreviation:  fufolio

URI for the subnamespace: http://folio.furman.edu/ctsns/cite2/fufolio

Summary description (one line) of the corpus identified by this subnamespace:  Data collections for research and teaching in the Department of Classics at Furman University.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: https://github.com/Eumaeus/fuCiteDX/blob/master/namespaces.md

**Comment by neelsmith** [comment]
The fufolio namespace has been added to the CITE2 subnamespace registry and will be published as part of the urn:cite2:cite:ctssns.v1: collection.
