### ISSUE TITLE
urn:cite2:botcar

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cite2-sns-registry#4]
Please supply the following information.

Subnamespace abbreviation:  botcar

URI for the subnamespace: http://folio.furman.edu/ctsns/cite2/botcar

Summary description (one line) of the corpus identified by this subnamespace:  Data collections of data related to the early scientific exploration of the Carolinas.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: https://github.com/Eumaeus/fuCiteDX/blob/master/namespaces.md

**Comment by neelsmith** [comment]
The botcar namespace has been added to the CITE2 subnamespace registry and will be published as part of the urn:cite2:cite:ctssns.v1: collection.
